version: "3.8"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    network_mode: "host"
    ports:
      - "9090:9090"
    volumes:
      - "./volumes/prometheus.yml:/etc/prometheus/prometheus.yml"
    privileged: true
    depends_on:
      - cadvisor

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    network_mode: "host"
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./volumes/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./volumes/dashboard/:/var/lib/grafana/dashboards/"
      - "./volumes/default.yaml:/etc/grafana/provisioning/dashboards/default.yaml"
    privileged: true
    depends_on:
      - prometheus

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    network_mode: "host"
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices:
      - "/dev/kmsg"

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    network_mode: "host"
    ports:
      - "9100:9100"
    volumes:
      - "/proc:/host/proc"
      - "/sys:/host/sys"
      - "/:/rootfs"
    privileged: true
    devices:
      - "/dev/kmsg"

  mysql-exporter:
    container_name: mysql-exporter
    image: prom/mysqld-exporter:latest
    network_mode: "host"
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=${MYSQL_EXPORTER_USER}:${MYSQL_EXPORTER_PASSWORD}@tcp(${MYSQL_EXPORTER_HOST}:${MYSQL_EXPORTER_PORT})/
    privileged: true

volumes:
  db_data:
  grafana-data:
